#############################################################################
#
#       Copyright (C) Microsoft Corporation 1991
#       All Rights Reserved.
#
#       Makefile for DEV\DDK\LIB\SRC\PCI directory
#
#############################################################################

FILES           = pci02z.asm pci03z.asm pci04z.asm

!include ..$(VWDIR)\src.mk
