#############################################################################
#
#       Copyright (C) Microsoft Corporation 1991
#       All Rights Reserved.
#
#       Makefile for DEV\DDK\LIB\SRC\CONFIGMG directory
#
#############################################################################

FILES		= cm02z.asm cm03z.asm cm04z.asm \
		  cm05z.asm cm06z.asm cm07z.asm cm08z.asm \
		  cm09z.asm cm0az.asm cm0bz.asm cm0cz.asm \
		  cm0dz.asm cm0ez.asm cm0fz.asm cm10z.asm \
		  cm11z.asm cm12z.asm cm13z.asm cm14z.asm \
		  cm15z.asm cm16z.asm cm17z.asm cm18z.asm \
		  cm19z.asm cm1az.asm cm1bz.asm cm1cz.asm \
		  cm1dz.asm cm1ez.asm cm1fz.asm cm20z.asm \
		  cm21z.asm cm22z.asm cm23z.asm cm24z.asm \
		  cm25z.asm cm26z.asm cm27z.asm cm28z.asm \
		  cm29z.asm cm2az.asm cm2bz.asm cm2cz.asm \
		  cm2dz.asm cm2ez.asm cm2fz.asm cm30z.asm \
		  cm31z.asm cm32z.asm cm33z.asm cm34z.asm \
		  cm35z.asm cm36z.asm cm37z.asm cm38z.asm \
		  cm39z.asm cm3az.asm cm3bz.asm cm3cz.asm \
		  cm3dz.asm cm3ez.asm cm3fz.asm cm40z.asm \
		  cm41z.asm cm42z.asm cm43z.asm cm44z.asm \
		  cm45z.asm cm46z.asm cm47z.asm cm48z.asm \
		  cm49z.asm cm4az.asm cm4bz.asm cm4cz.asm \
		  cm4dz.asm cm4ez.asm cm4fz.asm cm50z.asm \
		  cm51z.asm cm52z.asm cm53z.asm cm54z.asm \
		  cm55z.asm cm56z.asm cm57z.asm cm58z.asm \
		  cm59z.asm cm5az.asm cm5bz.asm cm5cz.asm \
		  cm5dz.asm cm5ez.asm cm5fz.asm cm60z.asm \
		  cm61z.asm cm62z.asm cm63z.asm cm64z.asm \
		  cm65z.asm cm66z.asm cm67z.asm cm68z.asm \
		  cm69z.asm cm6az.asm cm6bz.asm cm6cz.asm \
		  cm6dz.asm cm6ez.asm cm6fz.asm cm70z.asm \
		  cm71z.asm cm72z.asm cm73z.asm cm74z.asm \
		  cm75z.asm cm76z.asm cm77z.asm cm78z.asm \
		  cm79z.asm cm7az.asm cm7bz.asm

!include ..$(VWDIR)\src.mk

