/******************************Module*Header*******************************\
* Module Name: precomp.h
*
* Common headers used throughout the display driver.  This entire include
* file will typically be pre-compiled.
*
* Copyright (c) 1993-1995 Microsoft Corporation
\**************************************************************************/

#include <stddef.h>
#include <windows.h>
#include <winddi.h>
#include <devioctl.h>
#include <ntddvdeo.h>
#include <memory.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <ntsdexts.h>
#include <ioaccess.h>
#include <limits.h>
#include <rx.h>
#include <dciddi.h>

#include "lines.h"
#include "driver.h"
#include "hw.h"
#include "debug.h"
