copy 3dver.h           %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\3dver.h
copy BRDCONF.H         %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\BRDCONF.H
copy BRDCONF.INC       %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\BRDCONF.INC
copy CONTEXT.H         %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\CONTEXT.H
copy CONTEXT.INC       %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\CONTEXT.INC
copy dibeng.inc        %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\dibeng.inc
copy ereg.h            %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\ereg.h
copy gigitag.h         %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\gigitag.h
copy GLDDIF.H          %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\GLDDIF.H
copy GLDDTK.H          %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\GLDDTK.h
copy GLGLOBAL.H        %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\GLGLOBAL.H
copy glglobal.inc      %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\glglobal.inc
copy glinfo.inc        %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\glinfo.inc
copy glinfo.h          %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\glinfo.h
copy GLINTDEF.H        %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\GLINTDEF.H
copy GLINTDMA.H        %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\GLINTDMA.H
copy GLINTDMA.INC      %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\GLINTDMA.INC
copy GLINTESC.H        %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\GLINTESC.H
copy GLINTESC.INC      %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\GLINTESC.INC
copy GLINTFIX.H        %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\GLINTFIX.H
copy GLINTREG.H        %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\GLINTREG.H
copy GLINTREG.INC      %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\GLINTREG.INC
copy GLINTVER.H        %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\GLINTVER.H
copy linalloc.h        %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\linalloc.h
copy nodetool.h        %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\nodetool.h
copy p2info.h          %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\p2info.h
copy p2info.inc        %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\p2info.inc
copy p2string.h        %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\p2string.h
copy p2vidreg.h        %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\p2vidreg.h
copy p2vmicom.h        %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\p2vmicom.h
copy pmdef.h           %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\pmdef.h
copy ramdac.h          %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\ramdac.h
copy ramdac.inc        %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\ramdac.inc
copy Rgb525.h          %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\Rgb525.h
copy Rgb526.h          %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\Rgb526.h
copy Rgb528.h          %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\Rgb528.h
copy softcopy.h        %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\softcopy.h
copy tvp3026.h         %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\tvp3026.h
copy tvp4020.h         %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\tvp4020.h
copy valmode.inc       %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\valmode.inc
copy wgltrace.h        %DXDDKROOT%\display\samples\Dx\mini\3dlabsp2\inc\wgltrace.h
