#############################################################################
#
#       Copyright (C) Microsoft Corporation 1991
#       All Rights Reserved.
#
#       Makefile for DEV\DDK\LIB\SRC\PCCARD directory
#
#############################################################################

FILES		= pc03z.asm 

!include ..$(VWDIR)\src.mk

