#############################################################################
#
#       Copyright (C) Microsoft Corporation 1991
#       All Rights Reserved.
#
#       Makefile for DEV\DDK\LIB\SRC\VPOWERD directory
#
#############################################################################

FILES		= pw02z.asm pw03z.asm pw04z.asm \
		  pw05z.asm pw06z.asm pw07z.asm pw08z.asm \
		  pw09z.asm pw0az.asm pw0bz.asm pw0cz.asm \
		  pw0dz.asm

!include ..$(VWDIR)\src.mk

