/*
 * resource.h
 *
 * this contains resource type identifiers and some constants
 * used to name resources.
 *
 */

/*
 * resource types defined by this driver
 *
 */

#define MYFONT          258    /* PFM file */
#define PSPROC          259   /* PS Procset file */

#define IDS_ALL_NTM_FILES               0
#define IDS_FREEMEM                     1
#define IDS_HALFTONE                    2
#define IDS_NUMBER_TT_FONTS             3
#define IDS_FONT_SUBST_TABLE            4
#define IDS_FONT_SUBST_SIZE             5
#define IDS_TRAY_FORM_TABLE             6
#define IDS_TRAY_FORM_SIZE              7
