#############################################################################
#
#       Copyright (C) Microsoft Corporation 1991
#       All Rights Reserved.
#
#       Makefile for DEV\DDK\LIB\SRC\VMM directory
#
#############################################################################

FILES		= vmm01z.asm vmm02z.asm vmm03z.asm vmm04z.asm \
		  vmm05z.asm vmm06z.asm vmm07z.asm vmm08z.asm \
		  vmm09z.asm vmm0az.asm vmm0bz.asm vmm0cz.asm \
		  vmm0dz.asm vmm0ez.asm vmm0fz.asm vmm10z.asm \
		  vmm11z.asm vmm12z.asm vmm13z.asm vmm14z.asm \
		  vmm15z.asm vmm16z.asm vmm17z.asm vmm18z.asm \
		  vmm19z.asm vmm1az.asm vmm1bz.asm vmm1cz.asm \
		  vmm1dz.asm vmm1ez.asm vmm1fz.asm vmm20z.asm \
		  vmm21z.asm vmm22z.asm vmm23z.asm vmm24z.asm \
		  vmm25z.asm vmm26z.asm vmm27z.asm vmm28z.asm \
		  vmm29z.asm vmm2az.asm vmm2bz.asm vmm2cz.asm \
		  vmm2dz.asm vmm2ez.asm vmm2fz.asm vmm30z.asm \
		  vmm31z.asm vmm32z.asm vmm33z.asm vmm34z.asm \
		  vmm35z.asm vmm36z.asm vmm37z.asm vmm38z.asm \
		  vmm39z.asm vmm3az.asm vmm3bz.asm vmm3cz.asm \
		  vmm3dz.asm vmm3ez.asm vmm3fz.asm vmm40z.asm \
		  vmm41z.asm vmm42z.asm vmm43z.asm vmm44z.asm \
		  vmm45z.asm vmm46z.asm vmm47z.asm vmm48z.asm \
		  vmm49z.asm vmm4az.asm vmm4bz.asm vmm4cz.asm \
		  vmm4dz.asm vmm4ez.asm vmm4fz.asm \
		             vmm52z.asm vmm53z.asm vmm54z.asm \
		  vmm55z.asm vmm56z.asm vmm57z.asm vmm58z.asm \
		  vmm59z.asm vmm5az.asm \
		             vmm5ez.asm vmm5fz.asm vmm60z.asm \
		  vmm61z.asm vmm62z.asm vmm63z.asm vmm64z.asm \
		  vmm65z.asm vmm66z.asm vmm67z.asm vmm68z.asm \
		  vmm69z.asm vmm6az.asm vmm6bz.asm vmm6cz.asm \
		  vmm6dz.asm vmm6ez.asm vmm6fz.asm vmm70z.asm \
		  vmm71z.asm vmm72z.asm vmm73z.asm vmm74z.asm \
		  vmm75z.asm

!include ..$(VWDIR)\src.mk
