sed "/@@BEGIN_MSINTERNAL/,/@@END_MSINTERNAL/D" hardware.c   > %DXDDKROOT%\display\samples\Dx\minivdd\3dlabsp2\hardware.c 
sed "/@@BEGIN_MSINTERNAL/,/@@END_MSINTERNAL/D" i2c.c > %DXDDKROOT%\display\samples\Dx\minivdd\3dlabsp2\i2c.c 
sed "/@@BEGIN_MSINTERNAL/,/@@END_MSINTERNAL/D" init.c > %DXDDKROOT%\display\samples\Dx\minivdd\3dlabsp2\init.c 
sed "/@@BEGIN_MSINTERNAL/,/@@END_MSINTERNAL/D" ddkernel.c   > %DXDDKROOT%\display\samples\Dx\minivdd\3dlabsp2\ddkernel.c 
sed "/@@BEGIN_MSINTERNAL/,/@@END_MSINTERNAL/D" devctrl.c    > %DXDDKROOT%\display\samples\Dx\minivdd\3dlabsp2\devctrl.c 
sed "/@@BEGIN_MSINTERNAL/,/@@END_MSINTERNAL/D" reglog.c > %DXDDKROOT%\display\samples\Dx\minivdd\3dlabsp2\reglog.c 
sed "/@@BEGIN_MSINTERNAL/,/@@END_MSINTERNAL/D" vesa.c > %DXDDKROOT%\display\samples\Dx\minivdd\3dlabsp2\vesa.c 
sed "/@@BEGIN_MSINTERNAL/,/@@END_MSINTERNAL/D" vesaddc.c > %DXDDKROOT%\display\samples\Dx\minivdd\3dlabsp2\vesaddc.c 
sed "/@@BEGIN_MSINTERNAL/,/@@END_MSINTERNAL/D" video.c > %DXDDKROOT%\display\samples\Dx\minivdd\3dlabsp2\video.c 
sed "/@@BEGIN_MSINTERNAL/,/@@END_MSINTERNAL/D" writecmb.c > %DXDDKROOT%\display\samples\Dx\minivdd\3dlabsp2\writecmb.c 
sed "/@@BEGIN_MSINTERNAL/,/@@END_MSINTERNAL/D" devctrl.h    > %DXDDKROOT%\display\samples\Dx\minivdd\3dlabsp2\devctrl.h 
sed "/@@BEGIN_MSINTERNAL/,/@@END_MSINTERNAL/D" GLDEBUG.H    > %DXDDKROOT%\display\samples\Dx\minivdd\3dlabsp2\GLDEBUG.H 
sed "/@@BEGIN_MSINTERNAL/,/@@END_MSINTERNAL/D" glint.h      > %DXDDKROOT%\display\samples\Dx\minivdd\3dlabsp2\glint.h 
sed "/@@BEGIN_MSINTERNAL/,/@@END_MSINTERNAL/D" glint.inc    > %DXDDKROOT%\display\samples\Dx\minivdd\3dlabsp2\glint.inc 
sed "/@@BEGIN_MSINTERNAL/,/@@END_MSINTERNAL/D" glintmvd.asm > %DXDDKROOT%\display\samples\Dx\minivdd\3dlabsp2\glintmvd.asm 
sed "/@@BEGIN_MSINTERNAL/,/@@END_MSINTERNAL/D" mtrr.asm > %DXDDKROOT%\display\samples\Dx\minivdd\3dlabsp2\mtrr.asm 
sed "/@@BEGIN_MSINTERNAL/,/@@END_MSINTERNAL/D" makefile > %DXDDKROOT%\display\samples\Dx\minivdd\3dlabsp2\makefile 
sed "/@@BEGIN_MSINTERNAL/,/@@END_MSINTERNAL/D" glintmvd.rc > %DXDDKROOT%\display\samples\Dx\minivdd\3dlabsp2\glintmvd.rc 

