;****************************************************************************
;                                                                           *
; THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY     *
; KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE       *
; IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR     *
; PURPOSE.                                                                  *
;                                                                           *
; Copyright (C) 1993-95  Microsoft Corporation.  All Rights Reserved.       *
;                                                                           *
;****************************************************************************

;=========================================================================
;
; PORTINFO.INC
;
;=========================================================================	

; PORT Info Equates
	PORTName 	EQU	<'Generic Port Drv'> 	;Must be 16 chars
	PORTRev	EQU	00H
	PORTFeature	EQU	00H			
	PORT_IF	EQU	00H

; Helper VSD version equates

PORT_MAJOR_VERSION	EQU	4
PORT_MINOR_VERSION	EQU	0
