#############################################################################
#
#       Copyright (C) Microsoft Corporation 1991
#       All Rights Reserved.
#
#       Makefile for DEV\DDK\LIB\SRC\SHELL directory
#
#############################################################################

FILES		= shell01z.asm shell02z.asm shell03z.asm shell04z.asm \
		  shell05z.asm shell06z.asm shell07z.asm shell08z.asm \
		  shell09z.asm shell0az.asm shell0bz.asm shell0cz.asm \
		  shell0dz.asm shell0ez.asm

!include ..$(VWDIR)\src.mk

