#############################################################################
#
#       Copyright (C) Microsoft Corporation 1991
#       All Rights Reserved.
#
#       Makefile for DEV\DDK\LIB\SRC\VCOMM directory
#
#############################################################################

FILES		= vcomm02z.asm vcomm03z.asm vcomm04z.asm \
		  vcomm05z.asm vcomm06z.asm vcomm07z.asm vcomm08z.asm \
		  vcomm09z.asm vcomm0az.asm vcomm0bz.asm vcomm0cz.asm \
		  vcomm0dz.asm vcomm0ez.asm vcomm0fz.asm vcomm10z.asm \
		  vcomm11z.asm vcomm12z.asm vcomm13z.asm vcomm14z.asm \
		  vcomm15z.asm vcomm16z.asm vcomm17z.asm vcomm18z.asm \
		  vcomm19z.asm vcomm1az.asm vcomm1bz.asm vcomm1cz.asm \
		  vcomm1dz.asm vcomm1ez.asm vcomm1fz.asm vcomm20z.asm \
	          vcomm21z.asm

!include ..$(VWDIR)\src.mk

