/*++

Copyright (c) 1990-1995  Microsoft Corporation


Module Name:

    cpsuisam.h


Abstract:

    This module is the header file for the sample


Author:

    15-Jul-1996 Mon 13:44:10 created  -by-  Daniel Chou (danielc)


[Environment:]



[Notes:]


Revision History:


--*/


#define IDM_PERMISSION              10
#define IDM_USESTDABOUT             20
#define IDM_DOCPROP                 30
#define IDM_TVTEST                  40
#define IDM_DOCPROP_TVTEST          50

#define IDI_CPSUISAMPLE             500
#define IDI_APPLE                   510

#define PUSHBUTTON_DLG              1000
#define DLGABOUT                    1010
#define EXTPUSH_DLG                 1020
#define IDD_ABOUT1                  201
#define IDD_ABOUT2                  202
#define IDD_ABOUTICON               203
