#############################################################################
#
#       Copyright (C) Microsoft Corporation 1991
#       All Rights Reserved.
#
#       Makefile for DEV\DDK\LIB\SRC\VTD directory
#
#############################################################################

FILES		= vtd03z.asm vtd04z.asm \
		  vtd05z.asm

!include ..$(VWDIR)\src.mk

