;/******************************Module*Header**********************************\
; *
; *                           *****************************
; *                           * Permedia 2: SAMPLE CODE   *
; *                           *****************************
; *
; * Module Name: BRDCONF.INC
; *
; * Copyright (c) 1994-1998 3Dlabs Inc. Ltd. All rights reserved.
; * Copyright (c) 1995-1999 Microsoft Corporation.  All rights reserved.
; *
;\*****************************************************************************/

CHIP_SX         = 1
CHIP_FX         = 0
CHIP_TX         = 0

include glglobal.inc

; option casemap:notpublic

WANTSEGMENT = 1
include glintreg.inc
