#############################################################################
#
#       Copyright (C) Microsoft Corporation 1995
#       All Rights Reserved.
#
#       Makefile for DEV\DDK\LIB\SRC\CMD directory
#
#############################################################################

CFILES		= TRUE
OBJS		= cmd01.obj cmd02.obj cmd03.obj cmd07.obj

!include ..$(VWDIR)\src.mk

