#############################################################################
#
#       Copyright (C) Microsoft Corporation 1991
#       All Rights Reserved.
#
#       Makefile for DEV\DDK\LIB\SRC\IOS directory
#
#############################################################################

FILES		= ios01z.asm

!include ..$(VWDIR)\src.mk

