#############################################################################
#
#       Copyright (C) Microsoft Corporation 1991
#       All Rights Reserved.
#
#       Makefile for DEV\DDK\LIB\SRC\VXDLDR directory
#
#############################################################################

FILES		= dl02z.asm dl03z.asm dl04z.asm \
		  dl05z.asm dl06z.asm dl07z.asm dl08z.asm \
		  dl09z.asm dl0az.asm dl0bz.asm dl0cz.asm \
		  dl0dz.asm dl0ez.asm dl0fz.asm \
		  dl11z.asm dl12z.asm

!include ..$(VWDIR)\src.mk

