/****************************** Module Header ******************************\
* Module Name: kbdus.h
*
* Copyright (c) 1985-91, Microsoft Corporation
*
* Various defines for use by keyboard input code.
*
* History:
* 10-Jan-1991 GregoryW
* 23-Apr-1991 IanJa         VSC_TO_VK _* macros from oemtab.c
\***************************************************************************/

/*
 * kbd.h is for the USA.  There are no values to be overridden.
 */
#include "kbd.h"
