;******************************************************************************
;
;   (C) Copyright MICROSOFT Corp., 1990
;
;   Title:	VFINTD.INC
;
;   Version:	3.00
;
;   Date:	10-OCT-1990
;
;   Author:	nbs
;
;------------------------------------------------------------------------------
;
;   Change log:
;
;      DATE	REV		    DESCRIPTION
;   ----------- --- -----------------------------------------------------------
;
;==============================================================================

;
; This is the virtual device ID for this VxD.  It is a unique number assigned
; to this device.  For more information on VxD IDs, please see the VXDID.TXT
; file.
;
VFINTD_Dev_ID   equ    7fe5h
